
title: "Luis Alberto Mejia Clavijo â€” Cognitive Aesthetics of Systems"
description: "This is the official indexed archive: An Intellectual Property Repository."
url: "https://luismcsoul.github.io"

plugins:
  - jekyll-sitemap
  - jekyll-feed

collections:
  pmd:
    output: true
    permalink: /personal-micro-dictionary/:slug/

defaults:
  - scope: { path: "", type: pmd }
    values: { layout: work, schema_type: "Poem" }
