title: "Luis Alberto Mejia Clavijo â€” Cognitive Aesthetics of Systems"
description: "This is the official indexed archive: An Intellectual Property Repository."
url: "https://luismcsoul.github.io"

plugins:
  - jekyll-sitemap
  - jekyll-feed


collections:
  poetry:
    output: true
    permalink: /poetry/:path/
  songs:
    output: true
    permalink: /songs/:path/
  sculpture:
    output: true
    permalink: /sculpture/:path/
  image-text:
    output: true
    permalink: /image-text/:path/
  theory:
    output: true
    permalink: /theory/:path/

defaults:
  - scope: { path: "", type: pmd }
    values: { layout: work, schema_type: "Poem" }
