title: "Luis Alberto Mejia Clavijo â€” Cognitive Aesthetics of Systems"
description: "This is the official indexed archive: An Intellectual Property Repository."
url: "https://luismcsoul.github.io"

author: "Luis Alberto Mejia Clavijo"
aka: "luismcsoul"
project: "Cognitive Aesthetics of Systems"

plugins:
  - jekyll-sitemap
  - jekyll-feed

collections:
  written-photography:
    output: true
  sculpture:
    output: true
  songs:
    output: true
  taglines:
    output: true
  visualartwork:
    output: true
  article:
    output: true
  capsule-review:
    output: true
  epistolary:
    output: true
  personal-micro-dictionary:
    output: true
  photograph:
    output: true

permalink: /:collection/:slug/

defaults:
  - scope:
      path: ""
      type: songs
    values:
      layout: work
      schema_type: "MusicComposition"
  - scope:
      path: ""
      type: sculpture
    values:
      layout: work
      schema_type: "Sculpture"
  - scope:
      path: ""
      type: visualartwork
    values:
      layout: work
      schema_type: "VisualArtwork"
  - scope:
      path: ""
      type: epistolary
    values:
      layout: work
      schema_type: "CreativeWork"
  - scope:
      path: ""
      type: photograph
    values:
      layout: work
      schema_type: "Photograph"
