title: "Luis Alberto Mejia Clavijo â€” Cognitive Aesthetics of Systems"
description: "This is the official indexed archive: An Intellectual Property Repository."
url: "https://luismcsoul.github.io"

plugins:
  - jekyll-sitemap
  - jekyll-feed

collections:
  written-photography:
    output: true
  sculpture:
    output: true
  songs:
    output: true
  taglines:
    output: true
  visualartwork:
    output: true
  article:
    output: true
  capsule-review:
    output: true
  epistolary:
    output: true
  personal-micro-dictionary:
    output: true
  photograph:
    output: true

permalink: /:collection/:slug/

defaults:
  - scope: { path: "", type: pmd }
    values: { layout: work, schema_type: "Poem" }
